[package]
name = "gmail-fetch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imap = "2.4.1"
toml = "0.5.10"
serde = { version="1.0.152", features = ["derive"] }
native-tls = "0.2.11"